# Generated by Django 5.2.1 on 2025-08-13 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='tutor_usuario',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre': 'Tutor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='registro.usuario'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.alumno'),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('grado', 'seccion', 'ciclo_escolar')},
        ),
        migrations.AddField(
            model_name='asignacionmateria',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.grupo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.grupo'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.materia'),
        ),
        migrations.AddField(
            model_name='asignacionmateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.materia'),
        ),
        migrations.AddField(
            model_name='materia',
            name='materia_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.materiabase'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.grupo'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registro.usuario'),
        ),
        migrations.AddField(
            model_name='asignacionmateria',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.profesor'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('alumno', 'materia', 'trimestre')},
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('materia_base', 'grado')},
        ),
        migrations.AlterUniqueTogether(
            name='asignacionmateria',
            unique_together={('profesor', 'grupo', 'materia')},
        ),
    ]
